### ISSUE TITLE
TODO ddb

### ISSUE THREAD

**Issue by Toilal** [gfi-centre-ouest/docker-devbox#17]
`ddb` can now be installed for test purpose, it has been included in develop branch but is still uninstalled by default.

**Docs and installer**

- [ ] Add ddb to installer, using a flag to enable it (disabled, by default for now)
- [ ] Create docs website, using [mkdocs](https://www.mkdocs.org/)
- [ ] Add a migration page
- [ ] Add one doc page for each use case
- [ ] Add better description to features and action (pydoc)
- [ ] Replace docker-devbox-generator with cookiecutter templates, example projects or snippets

**New features**

- [x] Consistent configuration based on yml files and environment variables prefixed with `DDB_`
- [x] No bash dependency at all, various shell integration supported. 
- [x] Generate binaries from docker-compose label
- [x] Generate TLS certificates from docker-compose label
- [x] Watch mode with event driven programming (changes on template are instantly rendered)
- [x] Update `.gitignore` file automatically when rendered file is created/deleted
- [x] Detect when a template file is modified/deleted to update/delete rendered file, even when watch mode is not enabled.
 
**Features ported from bash scripts

- [x] Create symlinks based on environnement (`symlinks`)
- [x] Copy custom CA Certificates in build context of docker-compose services, or any other file (`copy` with dispatch option)
- [x] Generate reverse proxy configuration for domain name access (`jsonnet` + `traefik`)
- [x] Generate SSL certificate for development (`certs` + `traefik`)
- [x] Autoconfigure fixuid (`fixuid` when `fixuid.yml` is available in build context)
- [x] Automate docker-compose.resolved.yml generation for remote usage (Use `jsonnet` to generate a unique and already resolved docker-compose.yml)
- [x] Mo templates (replaced by `jinja`, `ytt` and `jsonnet`, opened to other template engine)
- [ ] Fix file access rights (chmod +x/-x) based on git index
- [ ] Add `DOCKER_VERSION` / `DOCKER_COMPOSE_VERSION` support
- [x] Disable traefik for generated binary shims (but should be disabled for commands that spaw a webserver, like npm run serve ...)
- [x] Activate automatically when entering in a directory containing `ddb.yml`, deactivate when leaving.
